test:test.c
	gcc -o $@ $^

signal:signal.c
	gcc -o $@ $^

sigact:sigact.c
	gcc -o $@ $^

mysleep:mysleep.c
	gcc -o $@ $^

mysleep1:mysleep1.c
	gcc -o $@ $^

return_test:return_test.c
	gcc -o $@ $^

sigchld:sigchld.c
	gcc -o $@ $^

.PHONY:clean
clean:
	rm test
